import 'models.dart';
import 'categories_model.dart';

List<Category> categories = [
  Category(
    name: 'Hot Meals',
    meals: [
      Meal(id: '1', name: 'Akara & Bread Special', price: 1000.0, category: 'Hot Meals',img:'assets/images/one.jpg' ,description:'Akara is a popular Nigerian snack made from black-eyed peas or beans. It is a deep-fried fritter with a crispy exterior and a soft, flavorful interior. The preparation involves grinding the beans into a paste, adding spices such as onions, peppers, and seasonings, and then deep-frying spoonfuls of the batter until golden brown. Akara is often served as a breakfast or snack item, enjoyed with a variety of accompaniments such as bread, pap (a cornmeal porridge), or as a filling in sandwiches. Its delightful taste and texture make it a beloved street food and a favorite choice for those craving a savory and satisfying treat.\nBread is a staple food enjoyed in various cultures around the world. It is a baked product typically made from wheat flour, water, yeast, and salt. Bread comes in a variety of shapes, sizes, and flavors, ranging from crusty baguettes to soft sandwich loaves. The process of bread-making involves kneading the dough to develop gluten, allowing it to rise through fermentation, and baking it to perfection. Bread is not only versatile but also serves as a foundation for countless culinary creations. It can be enjoyed on its own, toasted, or used to make sandwiches, burgers, or as a side with soups and stews. The aroma of freshly baked bread wafting through the air is irresistible, and biting into a warm slice with its soft crumb and crust is a delightful experience for bread lovers everywhere.' ),
      Meal(id: '2', name: 'Eko with Peppered Stew', price: 2000.0, category: 'Hot Meals',img: 'assets/images/two.jpg',description: 'Agidi, also known as Eko or Cornmeal Pudding, is a traditional Nigerian dish with a unique and comforting texture. It is made from cornmeal or maize flour, which is cooked to a gelatinous consistency and allowed to set into a solid block or mold. Agidi is often served alongside a flavorful and spicy stew, such as Peppered Stew.Peppered Stew is a rich and aromatic tomato-based stew infused with a variety of spices and peppers. It typically includes ingredients like tomatoes, onions, garlic, bell peppers, and a combination of scotch bonnet or habanero peppers, which give it a fiery kick. The stew is simmered to perfection, allowing the flavors to meld together and create a mouthwatering experience.When Agidi is paired with Peppered Stew, the contrast of textures and flavors is truly delightful. The smooth and slightly chewy Agidi provides a neutral base that complements the bold and spicy nature of the stew. Each bite of Agidi, dipped into the flavorful Peppered Stew, offers a burst of taste and a satisfying combination of textures.Agidi with Peppered Stew is a popular and beloved dish in Nigeria, enjoyed as a main course or a hearty snack. It represents the rich culinary heritage of the country and showcases the vibrant flavors and diverse ingredients used in Nigerian cuisine. Whether enjoyed at home or in local eateries, Agidi with Peppered Stew is a delicious and comforting meal that will leave you craving for more.'),
      Meal(id: '3', name: 'Abacha Special', price: 1400.0, category: 'Hot Meals',img: 'assets/images/three.jpg',description: 'Abacha, also known as African Salad, is a delightful Nigerian dish that brings together a medley of flavors and textures. It features dried and shredded cassava, which is rehydrated to create a unique base for the dish. Abacha is typically enjoyed as a cold salad, making it a refreshing choice for a hot day or a flavorful accompaniment to a meal.This traditional delicacy showcases the vibrant colors and aromatic ingredients that are synonymous with Nigerian cuisine. The rehydrated cassava flakes form the foundation of the salad, providing a soft and chewy texture. The combination of ingredients is what truly brings Abacha to life, with additions like ugba (oilbean), which adds a pleasant crunch and richness to every bite.\n As you savor each mouthful of Abacha, you nll encounter a tantalizing blend of flavors. The dressing, often made with palm oil, ground crayfish, and various seasonings, infuses the dish with a savory and slightly nutty taste. The interplay of spices and herbs adds depth, while the inclusion of vegetables and proteins complements the dish with their own distinct flavors.\nAbacha is a dish that exemplifies the diversity and creativity of Nigerian cuisine. Its presentation is visually striking, with vibrant ingredients and a colorful ensemble of flavors. Whether enjoyed as a light snack, a side dish, or a main course, Abacha invites you to experience the rich culinary heritage of Nigeria and embark on a delightful gastronomic journey.'),
      Meal(id: '4', name: 'Amala & Ewedu ', price: 1000.0, category: 'Hot Meals',img: 'assets/images/four.jpg',description: 'Amala and Ewedu are two popular Nigerian dishes often enjoyed together, showcasing the diverse and flavorful cuisine of the country.Amala is a traditional Nigerian swallow made from yam flour or cassava flour. It has a smooth, thick, and stretchy texture, similar to pounded yam. The process of making amala involves mixing the flour with hot water and kneading it until it forms a smooth, elastic dough. It is typically served in mounds or balls and is a staple accompaniment to various Nigerian soups and stews.Ewedu, on the other hand, is a delicious Nigerian soup made from jute leaves (Corchorus olitorius). The leaves are boiled and blended into a smooth consistency, creating a light and slightly slimy soup base. Ewedu is often flavored with traditional seasonings such as locust beans (iru), crayfish, and sometimes blended peppers for a hint of spiciness. It is commonly served alongside Amala and pairs exceptionally well with other Nigerian soups like Gbegiri (bean soup) and Gbegiri (palm fruit soup).The combination of Amala and Ewedu creates a harmonious and satisfying meal experience. The soft and malleable Amala serves as a perfect vessel for scooping up the flavorful Ewedu soup. The unique texture of Ewedu, combined with its delicate taste and aromatic seasonings, provides a refreshing contrast to the hearty Amala. When enjoyed together, they create a balanced and delicious blend of flavors that is loved by many Nigerians.Amala and Ewedu are not only a popular choice for home-cooked meals but can also be found in local restaurants and food stalls across Nigeria. This classic pairing represents the rich culinary heritage of the country and is a testament to the diversity and complexity of Nigerian cuisine.'),

    ],
  ),
  Category(
    name: 'Locals',
    meals: [
      Meal(id: '5', name: 'Ofada Rice', price: 1300.0, category: 'Locals',img:'assets/images/five.jpg' ,description:'Ofada is a traditional Nigerian dish that originates from the Yoruba ethnic group, specifically the town of Ofada in Ogun State. It is a flavorful and aromatic delicacy known for its unique combination of ingredients and rich taste.The key component of Ofada is the rice, which is a special variety of locally grown, unpolished rice known as Ofada rice. Unlike regular white rice, Ofada rice is partially or minimally processed, retaining its natural bran and germ. This gives it a distinct brownish color and a nutty flavor.Ofada rice is typically cooked using a special method that involves parboiling and further steaming to achieve a soft yet slightly chewy texture. It is usually served alongside a variety of flavorful accompaniments, making the dish truly special.One of the main accompaniments to Ofada rice is a delicious sauce known as Ofada sauce or Ayamase. This sauce is made from a blend of assorted peppers, such as green bell peppers and scotch bonnet peppers, along with onions, locust beans (iru), palm oil, and various spices. The combination of these ingredients creates a rich and spicy sauce with a deep flavor profile that perfectly complements the nutty taste of Ofada rice.In addition to the Ofada sauce, the dish is often served with assorted meat and fish, such as beef, cow skin (ponmo), smoked fish, or assorted offal. These protein components are usually cooked and seasoned separately, adding an extra layer of flavor and texture to the dish.Ofada is traditionally enjoyed by hand, with diners using their fingers to mix the rice and sauce together, creating a delightful medley of flavors. The combination of the nutty rice, spicy sauce, and tender meat or fish creates a satisfying and memorable culinary experience.Ofada is not only a delicious meal but also a representation of Nigerian culture and heritage. It is commonly served at special occasions, festivals, and gatherings, celebrating the rich culinary traditions of the Yoruba people and bringing people together through its delightful flavors.' ),
      Meal(id: '6', name: 'Ukwa Special', price: 2800.0, category: 'Locals',img: 'assets/images/six.jpg,',description: 'Ukwa, also known as African Breadfruit, is a popular Nigerian dish that is cherished for its unique taste and texture. It is made from the seeds of the African Breadfruit tree (Treculia africana) and is a staple in Igbo cuisine.The preparation of Ukwa involves several steps to make the seeds edible. First, the seeds are boiled or soaked in water for several hours to soften them and remove any bitterness. Then, the outer skins are peeled off, revealing the softer inner flesh. The peeled Ukwa seeds are boiled again until they become tender and can be easily mashed or eaten.Ukwa is known for its distinct flavor, which can be described as nutty and slightly sweet. The texture of the cooked seeds is soft and slightly chewy, reminiscent of cooked beans or legumes. It has a unique mouthfeel that adds to its appeal.In Nigerian cuisine, Ukwa is often prepared as a main dish or incorporated into various recipes. It can be used as an ingredient in soups, stews, or porridge-like dishes. Some common preparations include Ukwa soup, where the softened seeds are cooked with spices, palm oil, and other ingredients to create a flavorful soup. Ukwa can also be roasted or dried and used as a snack or added to other dishes for added texture and flavor.\n\nUkwa is not only enjoyed for its taste but also for its nutritional value. It is a good source of dietary fiber, protein, and essential nutrients, making it a nutritious addition to a balanced diet./n/nThis traditional Nigerian dish holds cultural significance, particularly among the Igbo people, and is often enjoyed during festive occasions, gatherings, or as a comforting meal. The rich flavor, unique texture, and versatility of Ukwa make it a cherished part of Nigerian culinary heritage.'),

    ],
  ),
  Category(
    name: 'Soups',
    meals: [
      Meal(id: '7', name: 'Egusi', price: 1000.0, category: 'Soups',img:'assets/images/eight.jpg' ,description:'Egusi Soup with Swallow.' ),
      Meal(id: '8', name: 'Afang ', price: 2000.0, category: 'Soups',img: 'assets/images/nine.jpg,',description: 'Afang Soup with Swallow'),

    ],
  ),
  Category(
    name: 'Soups',
    meals: [
      Meal(id: '7', name: 'Egusi', price: 1000.0, category: 'Soups',img:'assets/images/eight.jpg' ,description:'Egusi Soup with Swallow.' ),
      Meal(id: '8', name: 'Afang ', price: 2000.0, category: 'Soups',img: 'assets/images/nine.jpg,',description: 'Afang Soup with Swallow'),

    ],
  ),
  Category(
    name: 'Soups',
    meals: [
      Meal(id: '7', name: 'Egusi', price: 1000.0, category: 'Soups',img:'assets/images/eight.jpg' ,description:'Egusi Soup with Swallow.' ),
      Meal(id: '8', name: 'Afang ', price: 2000.0, category: 'Soups',img: 'assets/images/nine.jpg,',description: 'Afang Soup with Swallow'),

    ],
  ),

  // Add more categories and their products here as needed
];
